FROM node:12-alpine

COPY package.json yarn.lock /app/
WORKDIR /app
RUN yarn

COPY node /app/node
COPY src /app/src
COPY landing /app/landing
COPY webpack.js /app
RUN node webpack production

COPY server.js /app
COPY aws-upload.js /app

RUN npm run dev
